names=["anu","appu","sonu","brunda","chitra"]
num=[1,3,4,5,6]
# print(names)
# print(num)
# num.pop(1)
# print(num)
# print(len(names))
# print(max(num))
# print(min(num))
# print(max(names))
# print(min(names))
# print(tuple(names))
# names.append("kanchana")
print(names)
names.sort(reverse=True)
print(names)